[project]
name = "03-mcp"
version = "0.1.0"
description = "MCP server homework (Context7 clone)"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastmcp>=2.14.2",
    "numpy>=2.4.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "pytest>=9.0.2",
]
